name: 'Create pending github commit statuses'
description: Create a github commit status context in the pending state

inputs:
  github-token:
    description: "Github authentication token"
    required: true
  context:
    description: "Github status context"
    default: continuous-integration/github-actions/status
  target-url:
    description: "URL to include in the status"
    default: "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"

outputs:
  commit_status_sha:
    description: "The commit sha that the status is attached to"
    value: ${{ steps.commit_status_sha.outputs.sha }}

runs:
  using: "composite"
  steps:
    - name: Determine commit to put the build status on
      id: commit_status_sha
      shell: bash
      run: |
        if [[ "$GITHUB_EVENT_NAME" == "pull_request" ]]; then
          SHA="${{ github.event.pull_request.head.sha }}"
        else
          SHA="${{ github.sha }}"
        fi
        echo ::set-output name=sha::"$SHA"

    - name: Create commit status
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
        TARGET_URL: ${{ inputs.target-url }}
        COMMIT_STATUS_SHA: ${{ steps.commit_status_sha.outputs.sha }}
        DESCRIPTION: "Build status is pending"
        CONTEXT: ${{ inputs.context }}
      run: |
        declare -a ARGS
        if [[ -n "$TARGET_URL" ]]; then
            ARGS=("-f" "target_url=${TARGET_URL}")
        fi
        
        gh api "/repos/${GITHUB_REPOSITORY}/statuses/${COMMIT_STATUS_SHA}" \
           -X POST \
           -f state=pending \
           -f description="$DESCRIPTION" \
           -f context="$CONTEXT" \
           "${ARGS[@]}"
